In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'resume_score', 'lpa'])

In [3]:
df

cgpa  resume_score  lpa
0     8             8    4
1     7             9    5
2     6            10    6
3     5            12    7

In [5]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
model.get_weights()

[array([[-0.3093515 ,  0.59599876],
        [-0.35415983, -0.41308665]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.5023227],
        [1.147976 ]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
new_weights = [np.array([[0.1 ,  0.1],
        [0.1, 0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1],
        [0.1 ]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [14]:
model.set_weights(new_weights)

In [15]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [16]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [17]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=80, verbose=1, batch_size=1)

Epoch 1/80
4/4 [==============================] - 1s 3ms/step - loss: 27.9075
Epoch 2/80
4/4 [==============================] - 0s 2ms/step - loss: 27.5641
Epoch 3/80
4/4 [==============================] - 0s 2ms/step - loss: 27.2560
Epoch 4/80
4/4 [==============================] - 0s 3ms/step - loss: 26.9200
Epoch 5/80
4/4 [==============================] - 0s 2ms/step - loss: 26.5695
Epoch 6/80
4/4 [==============================] - 0s 3ms/step - loss: 26.2235
Epoch 7/80
4/4 [==============================] - 0s 2ms/step - loss: 25.8313
Epoch 8/80
4/4 [==============================] - 0s 3ms/step - loss: 25.4453
Epoch 9/80
4/4 [==============================] - 0s 2ms/step - loss: 25.0729
Epoch 10/80
4/4 [==============================] - 0s 2ms/step - loss: 24.6555
Epoch 11/80
4/4 [==============================] - 0s 3ms/step - loss: 24.2271
Epoch 12/80
4/4 [==============================] - 0s 2ms/step - loss: 23.8102
Epoch 13/80
4/4 [==============================] - 0s 2ms/ste

In [18]:
model.get_weights()

[array([[0.37863576, 0.37863576],
        [0.37278363, 0.37278363]], dtype=float32),
 array([0.27870044, 0.27870044], dtype=float32),
 array([[0.3794431],
        [0.3794431]], dtype=float32),
 array([0.20835708], dtype=float32)]